name: Bug report
description: Report something that is broken or incorrect.
labels: [bug]
body:
  - type: textarea
    id: what
    attributes:
      label: What happened?
      description: Include expected vs actual behavior.
    validations:
      required: true

  - type: textarea
    id: repro
    attributes:
      label: Steps to reproduce
      placeholder: "1. ...\n2. ...\n3. ..."
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Logs / stack traces
      description: Paste relevant console logs or stack traces.
      render: shell

  - type: input
    id: env
    attributes:
      label: Environment
      description: OS, Python version, Streamlit version.
