name: Feature request
description: Propose an enhancement.
labels: [enhancement]
body:
  - type: textarea
    id: idea
    attributes:
      label: What would you like to see?
      description: Describe the problem and the proposed solution.
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives
      description: Any alternatives you've considered.
